import { PropertyId, PropertyProperties, PropertyType } from "./types";

import { addressProperties, MoneyProperties } from "../types";
import { Money } from "@/domains/Money";
import { address } from "@/domains/Address";

export class Property {
  private constructor(
    private readonly id: PropertyId,
    private readonly centreImposition: string,
    private readonly description: string,
    private readonly price: MoneyProperties,
    private readonly state: number,
    private readonly hasAssensor: boolean,
    private readonly hasBalcony: boolean,
    private readonly hasCave: boolean,
    private readonly hasHealthCenterNearby: boolean,
    private readonly hasCollectiveHeating: boolean,
    private readonly hasPath: boolean,
    private readonly hasCollectiveHotWater: boolean,
    private readonly hasSchoolNearby: boolean,
    private readonly hasGreenSpace: boolean,
    private readonly hasGarage: boolean,
    private readonly hasSecurity: boolean,
    private readonly hasIntercom: boolean,
    private readonly hasDiningRoom: boolean,
    private readonly hasGrabageChute: boolean,
    private readonly favorite: string,
    private readonly frequence: string,
    private readonly numberOfBuilding: number,
    private readonly nombreEscalier: number,
    private readonly nombreEtage: number,
    private readonly nombrePieces: number,
    private readonly bathroomNumber: number,
    private readonly bedroomNumber: number,
    private readonly _address: addressProperties,
    private readonly status: number,
    private readonly surface: number,
    private readonly type: PropertyType,
    private readonly usage: number,
    private readonly userId: string,
    private readonly images: string[],
    private readonly video: string
  ) {}

  static fromProperties(properties: PropertyProperties) {
    const {
      id,
      centreImposition,
      description,
      price,
      state,
      hasAssensor,
      hasBalcony,
      hasCave,
      hasHealthCenterNearby,
      hasCollectiveHeating,
      hasPath,
      hasCollectiveHotWater,
      hasSchoolNearby,
      hasGreenSpace,
      hasGarage,
      hasSecurity,
      hasIntercom,
      hasDiningRoom,
      hasGrabageChute,
      favorite,
      frequence,
      numberOfBuilding,
      nombreEscalier,
      nombreEtage,
      nombrePieces,
      bathroomNumber,
      bedroomNumber,
      address,
      status,
      surface,
      type,
      usage,
      userId,
      images,
      video
    } = properties;

    return new Property(
      id,
      centreImposition,
      description,
      price,
      state,
      hasAssensor,
      hasBalcony,
      hasCave,
      hasHealthCenterNearby,
      hasCollectiveHeating,
      hasPath,
      hasCollectiveHotWater,
      hasSchoolNearby,
      hasGreenSpace,
      hasGarage,
      hasSecurity,
      hasIntercom,
      hasDiningRoom,
      hasGrabageChute,
      favorite,
      frequence,
      numberOfBuilding,
      nombreEscalier,
      nombreEtage,
      nombrePieces,
      bathroomNumber,
      bedroomNumber,
      address,
      status,
      surface,
      type,
      usage,
      userId,
      images,
      video,
    );
  }

  get properties(): PropertyProperties {
    return {
      id: this.id,
      centreImposition: this.centreImposition,
      description: this.description,
      price: new Money(this.price),
      state: this.state,
      hasAssensor: this.hasAssensor,
      hasBalcony: this.hasBalcony,
      hasCave: this.hasCave,
      hasHealthCenterNearby: this.hasHealthCenterNearby,
      hasCollectiveHeating: this.hasCollectiveHeating,
      hasPath: this.hasPath,
      hasCollectiveHotWater: this.hasCollectiveHotWater,
      hasSchoolNearby: this.hasSchoolNearby,
      hasGreenSpace: this.hasGreenSpace,
      hasGarage: this.hasGarage,
      hasSecurity: this.hasSecurity,
      hasIntercom: this.hasIntercom,
      hasDiningRoom: this.hasDiningRoom,
      hasGrabageChute: this.hasGrabageChute,
      favorite: this.favorite,
      frequence: this.frequence,
      numberOfBuilding: this.numberOfBuilding,
      nombreEscalier: this.nombreEscalier,
      nombreEtage: this.nombreEtage,
      nombrePieces: this.nombrePieces,
      bathroomNumber: this.bathroomNumber,
      bedroomNumber: this.bedroomNumber,
      address: this._address,
      status: this.status,
      surface: this.surface,
      type: this.type,
      usage: this.usage,
      userId: this.userId,
      images: this.images,
      video: this.video,
    };
  }

  get address(): address{
    return new address(this._address);
  }
}
